window.MISOLABO_DEFAULT_PLAYLISTS = [
  {
    id: 'pickup-first-inami',
    name: 'はじめての伊波ライ',
    description: '管理人が独断で選ぶ、伊波ライ入門編。\nデュエット・バンド演奏・弾き語り・3Dライブまで、いろんな魅力が詰まっています。気が向いたらぜひ。\n定期的に更新していきます。',
    badge: 'PICK UP',
    songRefs: [
      { videoId: 'eXSc32j4meE', title: 'ワールド・ランプシェード', artist: 'buzzG' },
      { videoId: '2SPEfidEBVc', title: 'ファンサ', artist: 'mona(cv.夏川椎菜)' },
      { videoId: 'WL5rE9BgzUo', title: '気づけよBaby', artist: 'THE ORAL CIGARETTES' },
      { videoId: '5ESXILcf1j4', title: 'ドリームレス・ドリームス', artist: 'はるまきごはん' },
      { videoId: 'XwI3P-QZQzc', title: '地球をあげる', artist: 'はるまきごはん' },
      { videoId: 'rbTSSeKrZUc', title: '月光', artist: 'キタニタツヤ × はるまきごはん' },
      { videoId: 'ZRhe1FZbLGY', title: '空っぽなら、踊ろうぜ', artist: 'Guiano × 理芽' },
      { videoId: 'O7yLcJUqQgM', title: '偽物人間40号', artist: '¿?shimon' },
      { videoId: 'HCWHHDmebLE', title: 'エゴロック', artist: 'すりぃ' },
      { videoId: 'uLhtxdCx62g', title: '砂の惑星', artist: 'ハチ' },
      { videoId: 'Y2L4M9LImEI', title: 'カタオモイ', artist: 'Aimer' },
      { videoId: 'Y2L4M9LImEI', title: 'ファタール', artist: 'GEMN' },
      { videoId: '80B4Umv8zZ8', title: 'Ginger', artist: 'TOMOO' },
      { videoId: 'hejKRnC8Dv8', title: 'ドクトリーヌ', artist: '煮ル果実' },
      { videoId: '7ynYCHj13wI', title: '欲望に満ちた青年団', artist: 'ONE OK ROCK' },
      { videoId: '1dsNzm5CY_U', title: '東京フラッシュ', artist: 'Vaundy' },
      { videoId: 'F0RWoCiWb5o', title: '裸の勇者', artist: 'Vaundy' },
      { videoId: '80laTCdX1lQ', title: 'Booo!', artist: 'TOKOTOKO（西沢さんP）' },
      { videoId: '80laTCdX1lQ', title: '藍', artist: 'スキマスイッチ' },
      { videoId: 'mCITW9_7uOw', title: '朝を呑む', artist: '須田景凪' },
      { videoId: 'QjUHV8IWzZo', title: 'モニタリング', artist: 'Deco*27' },
      { videoId: 'L9Hl84VAM8I', title: 'イドラのサーカス', artist: 'Neru' },
      { videoId: 'gc8cMgp_3Pc', title: '獣ゆく細道', artist: '椎名林檎と宮本浩次' },
      { videoId: 'bfjmfFyFdoI', title: '告白', artist: '崎山蒼志 × 石崎ひゅーい' },
      { videoId: 'bfjmfFyFdoI', title: '夢遊病者は此岸にて', artist: 'こんにちは谷田さん' },
      { videoId: 'KuSrrDSXHpQ', title: 'JANE DOE', artist: '米津玄師 × 宇多田ヒカル' },
      { videoId: 'I8WpTr4ic-Q', title: '点描の唄', artist: 'Mrs. GREEN APPLE' },
      { videoId: '_alEzJhQsSg', title: '手紙', artist: 'フジファブリック' },
      { videoId: '80laTCdX1lQ', title: 'レイオブライト', artist: '伊波ライ' },
      { videoId: 'UUFIAi9U89M', title: 'Diary', artist: 'SEKAI NO OWARI' },
      { videoId: '1dsNzm5CY_U', title: 'napori', artist: 'Vaundy' },
      { videoId: 'mCITW9_7uOw', title: '長く短い祭', artist: '椎名林檎' },
    ],
  },
];
